version: '3.8'

services:
  gewe:
    container_name: gewe
    image: gewe
    command: /usr/sbin/init
    privileged: true
    networks:
      - astrbot_network
    ports:
      - "2531:2531"  # 主机端口与容器端口映射
      - "2532:2532"
    volumes:
      - "/root/docker/gewtchat_data:/root/temp" 
    stdin_open: true  # 对应 -i 参数
    tty: true        # 对应 -t 参数 分配伪终端

  astrbot:
    image: my_astrbot:latest
    container_name: astrbot
    ports: # mappings description: https://github.com/Soulter/AstrBot/issues/497
      - "6180-6200:6180-6200"
      - "11451:11451" # optional, gewechat default port
    volumes:
      - /root/docker/astrbot_data:/AstrBot/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - astrbot_network


networks:
  astrbot_network:
    name: astrbot_network
    driver: bridge
