version: '3.8'

# 当接入 QQ NapCat 时，请使用这个 compose 文件一键部署: https://github.com/NapNeko/NapCat-Docker/blob/main/compose/astrbot.yml

services:
  gewe:
    container_name: gewe
    image: gewe
    command: /usr/sbin/init
    privileged: true
    networks:
      - astrbot_network
    ports:
      - "2531:2531"  # 主机端口与容器端口映射
      - "2532:2532"
    volumes:
      - "/root/docker/gewtchat_data:/root/temp"
    stdin_open: true  # 对应 -i 参数
    tty: true        # 对应 -t 参数 分配伪终端

  astrbot:
    image: my_astrbot:latest
    container_name: astrbot
    restart: always
    ports: # mappings description: https://github.com/Soulter/AstrBot/issues/497
      - "6185:6185" # 必选，AstrBot WebUI 端口
      - "6195:6195" # 可选, 企业微信 Webhook 端口
      - "6199:6199" # 可选, QQ 个人号 WebSocket 端口
      - "6196:6196" # 可选, QQ 官方接口 Webhook 端口
      - "11451:11451" # 可选, 微信个人号 Webhook 端口
    volumes:
      - /root/docker/astrbot_data:/AstrBot/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - astrbot_network


networks:
  astrbot_network:
    name: astrbot_network
    driver: bridge
