version: '3.8'

services:
  astrbot:
    image: my_astrbot:latest
    container_name: astrbot
    ports: # mappings description: https://github.com/Soulter/AstrBot/issues/497
      - "6180-6200:6180-6200"
      - "11451:11451" # optional, gewechat default port
    volumes:
      - /root/docker/astrbot_data:/AstrBot/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - astrbot_network



  gewe:
    image: gewe
    container_name: gewe
    volumes:
      - /root/docker/gewtchat_data:/root/temp
    ports:
      - "2531:2531"
      - "2532:2532"
    restart: always
    networks:
      - astrbot_network

networks:
  astrbot_network:
    name: astrbot_network
    driver: bridge

